# fly.toml app configuration file generated for aiapipro-blog on 2023-08-14T16:38:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aiapipro-blog"
primary_region = "ams"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
